config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end
resources :conversations do
  resources :messages
 end
  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    mount ActionCable.server => '/cable'

  root "temp#index"

  # For fb login
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
    require 'carrierwave/orm/activerecord'
end

app/models/conversation.rb
class Conversation < ActiveRecord::Base
 belongs_to :user, :foreign_key => :sender_id
 belongs_to :user, :foreign_key => :recipient_id

has_many :messages, dependent: :destroy

validates_uniqueness_of :sender_id, :scope => :recipient_id

def between(sender_id,recipient_id)
end	


scope :between, -> (sender_id,recipient_id) do
 where('(conversations.sender_id = ? AND conversations.recipient_id = ? ) OR (conversations.sender_id = ? AND conversations.recipient_id = ? )', sender_id,recipient_id, recipient_id, sender_id)
 end

end

app/models/message.rb
class Message < ActiveRecord::Base
 belongs_to :conversation
 belongs_to :user

 validates_presence_of :body, :conversation_id, :user_id
after_create_commit { MessageBroadcastJob.perform_later(self) }
 def message_time
  created_at.strftime('%m/%d/%y at %l:%M %p')
 end

   def timestamp
    created_at.strftime('%H:%M:%S %d %B %Y')
  end

end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  mount_uploader :avatar, AvatarUploader
  has_many :conversations, dependent: :destroy
  # def self.from_omniauth(auth)
  #   where(auth.slice(:privider, :uid)).first_or_initialize.tap do |user|
  #     user.provider = auth.provider
  #     user.uid = auth.uid
  #     user.name = auth.info.name
  #     user.auth_token = auth.credentials.token
  #     user.oauth_expires_at = Time.at(auth.credentials.expires_at)
  #     user.save
  #   end
  # end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid      = auth.uid
      user.name     = auth.info.name
      user.email  = auth.uid.to_s + "@dummy.com"
      user.encrypted_password = ""
      user.save(:validate => false)
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller

  protect_from_forgery with: :exception
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
	before_action :require_login

def index
 @users = User.all
 @conversations = Conversation.all
 end

 def new
 	@conversation= Conversation.new
 end

def create
 if Conversation.between(params[:sender_id],params[:recipient_id])
   .present?
    @conversation = Conversation.between(params[:sender_id],
     params[:recipient_id]).first
 else
  @conversation = Conversation.create!(conversation_params)
 end

 redirect_to conversation_messages_path(@conversation)

end

private
 def conversation_params
  params.permit(:sender_id, :recipient_id)
 end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_action do
   @conversation = Conversation.find(params[:conversation_id])
  end

def index
  @conversation= Conversation.find(params[:conversation_id])
 @messages = @conversation.messages
  if @messages.length > 10
   @over_ten = true
   @messages = @messages[-10..-1]
  end
  if params[:m]
   @over_ten = false
   @messages = @conversation.messages
  end
 if @messages.last
  if @messages.last.user_id != current_user.id
   @messages.last.read = true;
  end
 end

@message = @conversation.messages.new
 end

def new
 @message = @conversation.messages.new
end

def create
 @message = @conversation.messages.new(message_params)
 if @message.save
  redirect_to conversation_messages_path(@conversation)
 end
end

private
 def message_params
  params.require(:message).permit(:body, :user_id)
 end
end

app/controllers/sessions_controller.rb
class SessionsController <  < Clearance::SessionsController
  def create
    if env["omniauth.auth"].present?
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end
  end
end

app/controllers/temp_controller.rb
class TempController < ApplicationController
	before_action :require_login
	def index
	end
end

app/controllers/users_controller.rb
class UsersController < < Clearance::UsersController

	def new
	  @user=User.new
	  uploader = AvatarUploader.new
	end



def user_params
    params.require(:user).permit(:email, :avatar,:sender_id,:recipient_id)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
	def bootstrap_class_for flash_type
		{success: 'alert-success', error: 'alert-danger', notice:'alert-warning'}[flash_type.to_sym]
	end

	def flash_messages (opt={})
		flash.map do |msg_type, message|
			content_tag(:div, message,class: "alert #{bootstrap_class_for(msg_type)} fade in") do
				content_tag(:button, 'x'.html_safe, class:'close', data: {dismiss: 'alert'}) + message
			end
		end.join.html_safe
	end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/temp_helper.rb
module TempHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/conversations/index.html.erb
<div class='ui segment'>
 <h3>Mailbox</h3>

 <div class='ui list'>
  <div class='item'>
   <% @conversations.each do |conversation| %>
   <% if conversation.sender_id == current_user.id || conversation.recipient_id == current_user.id %>
    <% if conversation.sender_id == current_user.id %>
      <% recipient = User.find(conversation.recipient_id) %>
    <% else %>
      <% recipient = User.find(conversation.sender_id) %>
    <% end %>
    <%= link_to recipient.email,   conversation_messages_path(conversation)%>
   <% end %>
  <% end %>
  </div>
 </div>
</div>

<div class='ui segment'>
 <h3>All Users</h3>
  <div class='ui list'>
   <% @users.each do |user| %>
    <% if user.id != current_user.id %>
     <div class='item'>
   <%= user.email %> <%= link_to 'Message me!', conversations_path(sender_id: current_user.id, recipient_id: user.id), method: 'post'%>
 </div>
  <% end %>
 <% end %>
 </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>EGuru</title>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= csrf_meta_tag %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  
</head>
<body>
  <div id="header">

      <nav class="navbar navbar-light bg-faded">
        <div class="navbar-content">
          <button class="navbar-toggler hidden-sm-up" type="button" data-toggle="collapse" data-target="#navbar-header" aria-controls="navbar-header" aria-expanded="false" aria-label="Toggle navigation"></button>
          <%= link_to root_path, class: 'navbar-brand' do %>
            <img src="https://raw.githubusercontent.com/HLVA/eGuru/master/src/app/assets/images/eGuruLogo.png" class="eguru-logo">
          <% end %>
          <div class="collapse navbar-toggleable-xs" id="navbar-header">

            <ul class="nav navbar-nav">
              <li class="nav-item">
                <%= link_to 'Home', root_path, class:"" %>
              </li>
              <li class="nav-item float-xs-right">
                <% if signed_in? -%>
                  <%= link_to t(".sign_out"), sign_out_path, method: :delete %>
                <% else -%>
                  <%= link_to t(".sign_in"), sign_in_path %>
                <% end -%>
              </li>
            </ul>
          </div>
        </div>
      </nav> <!-- /navbar -->
  </div>

  <div class="container content">
    <%= flash_messages %>
    <%= yield %>
  </div>

  <footer class="text-xs-center">
    <p>&copy; eGuru - Developed by HLVA Team</p>
  </footer>

</body>
</html>

app/views/messages/_message.html.erb
<div class="card">
  <div class="card-block">
    <div class="row">
      <div class="col-md-1">
      </div>
      <div class="col-md-11">
        <p class="card-text">
          <span class="text-muted"><%= message.user.email %> at <%= message.timestamp %> says</span><br>
          <%= message.body %>
        </p>
      </div>
    </div>

  </div>
</div>

app/views/messages/index.html.erb
<div class="container">
  <div class="row">
<% if @over_ten %>
 <%= link_to 'Show Previous', '?m=all' %>
<% end %>

<div class='messages' data-chat-room-id="<%= params[:conversation_id]%>">
 <% @messages.each do |message| %>
  <% if message.body %>
   <% user = User.find(message.user_id) %>
   <div class='item'>
    <div class='content'>
     <div class='header'><strong><%= user.email %></strong>     <%= message.message_time %></div>
      <div class='list'>
       <div class='item'>
        <i class='right triangle icon'></i>
         <%= message.body %>
      </div>
    </div>
   </div>
 </div>
 <% end %>
<% end %>
</div>

<%= form_for [@conversation, @message], html: {class: 'ui reply form'} do |f| %>
   <%= hidden_field_tag 'chat_room_id', params[:conversation_id] %>
  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control' %>
    <small class="text-muted">From 2 to 1000 characters</small>
  </div>
 <%= f.text_field :user_id, value: current_user.id, type: 'hidden' %>
 <div>
   <%= f.submit 'Add Reply', class: 'ui blue labeled submit icon button' %>
 </div>

<% end %>

</div>
</div>

app/views/temp/index.html.erb
<script src="http://maps.google.com/maps/api/js?key=AIzaSyCV3IGNl6r2CRGac1Ce4W5QL6G_1lBSRYc"></script>
  <script src="http://cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
  <script src='http://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->
<%= link_to "Home page",root_path, class:"btn btn-primary" %>
<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>
<script type="text/javascript">
	handler = Gmaps.build('Google');
	handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
	  markers = handler.addMarkers([
	    {
	      "lat": 0,
	      "lng": 0,
	      "picture": {
	        "url": "http://people.mozilla.com/~faaborg/files/shiretoko/firefoxIcon/firefox-32.png",
	        "width":  32,
	        "height": 32
	      },
	      "infowindow": "hello!"
	    }
	  ]);
	  handler.bounds.extendWith(markers);
	  handler.getMap().setZoom(1);
	  // handler.fitMapToBounds();
	});	
</script>

app/views/users/_form.html.erb
<div class="form-group row">
  <%= form.label :email, class:"col-sm-3" %>
  <%= form.text_field :email, type: 'email', class:"col-sm-9" %>
</div>

<div class="form-group row">
  <%= form.label :password, class:"col-sm-3" %>
  <%= form.password_field :password, class:"col-sm-9" %>
</div>

<div class="form-group row">
  <%= form.submit "Signup", class:"btn btn-primary col-sm-2 offset-sm-3" %>
  <%= link_to t(".sign_in"), sign_in_path, class:"col-sm-4" %>
</div>

app/views/users/new.html.erb
<div class="row">
	<div class="col-md-6 offset-md-3">

		<div class="user-sign-form">
			<div id="clearance" class="sign-up">
			  <div class="row">
				  <div class="col-md-6 offset-md-3 text-xs-center">
				  	<h2><%= t(".title") %></h2>	
				  </div>
			  </div>
			  
				<div class="container" >
				  <%= form_for @user do |form| %>
				    <%= render partial: '/users/form', object: form %>
				  <% end %>
				</div>
			</div>
		</div>
	</div>
</div>